version: '3.0'
services:
  postgres:
    image: postgres:11
    volumes:
        - ${REVDEBUG_VOLUME_PATH:-/var/revdebug/server/repo}/revdebug_database:/var/lib/postgresql/data
    environment:
            POSTGRES_USER: ${REVDEBUG_POSTGRES_USER:-rdb_user}
            POSTGRES_PASSWORD: ${REVDEBUG_POSTGRES_PASSWORD:-masterkey}
            POSTGRES_DB: ${REVDEBUG_POSTGRES_DATABASE:-DevOpsMonitor}
  devops:
    image: docker.revdebug.com/devops:latest
    ports:
        - "${REVDEBUG_MONITOR_PORT:-5000}:5000"
        - "${REVDEBUG_RECORDERS_PORT:-42733}:42733"
        - "${REVDEBUG_APPLICATIONS_PORT:-42734}:42734"
    volumes:
        - ${REVDEBUG_VOLUME_PATH:-/var/revdebug/server/repo}:/app/RevDeBug
    environment:
            REVDEBUG_AUTH: ${REVDEBUG_AUTH}
            REVDEBUG_POSTGRES_SERVER: ${REVDEBUG_POSTGRES_SERVER:-postgres}
            REVDEBUG_POSTGRES_PORT: ${REVDEBUG_POSTGRES_PORT:-5432}
            REVDEBUG_POSTGRES_USER: ${REVDEBUG_POSTGRES_USER:-rdb_user}
            REVDEBUG_POSTGRES_PASSWORD: ${REVDEBUG_POSTGRES_PASSWORD:-masterkey}
            REVDEBUG_POSTGRES_DATABASE: ${REVDEBUG_POSTGRES_DATABASE:-DevOpsMonitor}
    links:
            - postgres